@startuml classdiagram
skinparam Linetype ortho
skinparam groupInheritance 2

note as N1
In this diagram we are showing the classes and their methods that are used in the Allergens Dietary Ictoria plugin.
and not any WordPress core classes or methods.
Likewise with Woocommerce.
end note

note as N2
The file called Allergens_Dietary is the main file for the plugin.
But contains 2 classes these must be separated in a later rendition of the plugin.
This to support the Single Responsibility Principle and maintain clean code.
end note

note as N3
All classes that do not have a relation are pure singleton classes.
Meaning there can only be one instance of the object at any given time.
end note

package "php"{

    class Allergens_Dietary_Filter{
        -{static} _instance : Allergens_Dietary_Filter
        - _allergens : array
        +{static} instance() : Allergens_Dietary_Filter
        - __construct() : void
        + create_filter() : void
        + filter_query(query:array) : void
        + load_css() : void
        + load_js() : void
    }

    class Allergens_Dietary_Activator{
        -{static} counter: int
        -{static} url: string
        -{static} allergens_options: array
        -{static} allergy_icon_options: array
        -{static} icon_options: array
        +{static} activate() : void
        + __construct() : void
        -{static} create_tables() : void
        +{static} load_textdomain() : void
        +{static} get_settings() : array
        +{static} get_options() : array
        +{static} load_style() : void
        +{static} enqueue_styles() : void
        +{static} enqueue_admin_styles() : void
        +{static} load_admin_js() : void
        +{static} enqueue_admin_scripts() : void
        + upload_language_file() : void
        +{static} initialize() : void
        +{static} allergens_options() : array
        +{static} allergy_icon_options() : array
        +{static} icon_options() : array
        +{static} insert_standard_data() : void
    }

    class Allergens_Dietary_Product_Settings{
        -{static} _instance : Allergens_Dietary_Product_Settings
        - _allergens :array
        - _allergy_attachments : array  
        + __construct() : void
        + data_tab(product_data_tabs:array) : array
        + data_fields() : void
        + save_product_options(post_id:int) : void
        - replace_space_chars(allergens:string) : string
    }

    class Allergens_Dietary_Products{
        -{static} _instance : Allergens_Dietary_Products
        +{static} instance() : Allergens_Dietary_Products
        + __construct() : void
        + show_product_options() : void
        + render_html(data:array): string

    }

    class Allergens_Dietary_Wc_Integration_Settings{
        + __construct() : void
        + init_form_fields() : void
        + generate_allergensdietary_html() : void
        + save_settings(post:array) : void
        +{static} plugin_action_links(links:array) : array
    }
    package "tables"{
         class Allergens_Dietary_Show_Allergens{
            - {static} _instance : array
            # {static} _page : int
            # {static} message : string
            # __construct() : void
            # display_tablenav(which:string) : void
            # table_action_options : array
            + search_query : string
            + get_table_columns_and_data() : array
            + get_items_per_pages() : int
            # set_items_per_pages(value:int) : void
            + column_default(item:array, column_name:string) : string
            + column_cb(item:array) : string
            + single_row(item:array) : void
            + get_bulk_actions() : array
            # edit_row_action(id:string) : string
            + handle_row_actions(item:array, column_name:string, primary:string) : array
            # build_action_url(action:string, item:array) : string
            # handle_search() : void
            # handle_items_per_page() : void
            # single_row_columns(item:object) : void
            + get_columns() : array
            + prepare_items() : void
            + process_quick_action() : void
            + process_bulk_action(data:array) : void
            + items_per_page_form(text:string, input_id:string, label:string, which:string) : void
            + search_box(text:string, input_id:string) : voi
            + {static} getInstance() : self
            + table_page() : void
        }
    }
    package "notice"{

        enum NoticeTypes{
            ERROR
            INFO
            SUCCESS
            NOTICE
        }

        class Allergens_Dietary_Notices{
            -{static} _instance : Allergens_Dietary_Notices
            + getInstance(): Allergens_Dietary_Notices
            # __construct():void 
            + display_notice(type:NoticeType, message:string) : void
        }

    }

    package "forms"{

        enum FormType{
            ALLERGENS
            LICENSE
            UPDATE

            + match(formType:FormType) : boolean
        }

        interface I_Allergens_Dietary_Form{
            + showForm(allergenName:String) : void
            + submit(data:array) : void
            + sanitize(data:array) : array
        }

        class Allergens_Dietary_Form{
            -{static} _instance : array
            #{static} formType : FormType
            #{static} formObject : I_Allergens_Dietary_Form
            # __construct() : void
            + {static} getInstance() : self
            + {static} setFormType(formType:FormType) : void
            + {static} getFormType() : FormType
            + submitUpdate() : void
            + showForm(allergenName:String) : void
        }

        class Allergens_Dietary_License_Form{
            + __construct(): void
            + showForm(allergenName:String) : void
            + submit(data:array) : void
            + sanitize(data:array) : array
        }
    }

    package "DB" {
        class Allergens_Dietary_Allergen_Queries{
            -{static} instances : array
            +{static} getInstance() : self
            # __construct() : void
            + getAllAllergens() : array
            + {static} includeItems() : void
            + {static} is_default_allergen(allergy_name:string) : boolean
            + {static} getItems() : array
            + {static} getColumns() : array
            + {static} activationUpdate(data:array) : void
            + {static} singleActivationUpdate() : void
        }

        class Allergens_Dietary_Attachment_Queries{
            -{static} instances : array
            +{static} getInstance() : self
            # __construct() : void
            + {static} attachment_insert(result:array) : void
        }

        class Allergens_Dietary_Allergy_Attachment_Queries{
            -{static} instances : array
            +{static} getInstance() : self
            # __construct() : void
            + getAllergyAttachment(allergyAttachmentName:string, isForm:boolean) : array
            + getAllAllergyAttachmments(skip_default:boolean) : array
            + {static} allergy_connection(result:array) : array
        }
        class Allergens_Dietary_Allergy_Product_Queries{
            -{static} instances : array
            +{static} getInstance() : self
            # __construct() : void
            + addAllergyProduct(product_id:int, allergen:string) : boolean
            + getAllergyProduct(product_id:int, allergen:string=null) : array
            + deleteAllergyProduct(product_id:int, allergen:String) : boolean
            + getFilteredProducts(allergens:array, dietary:array) : array
        }
    }
    package "lists" {
        class Allergens_Dietary_Info{
            # {static} _instance : Allergens_Dietary_Tabs
            + showinfo() : void
            + {static} getInstance() : Allergens_Dietary_Info
            + {static} getStyles() : void
        }
    }

    package "tabs" {
        class Allergens_Dietary_Tabs{
            - {static} instances : array
            + showtabs() : void
            + showpages() : void
            + {static} getInstance() : self
            + {static} getStyles() : void

        }
    }  
}

package Allergens_Dietary{
    class load_language{
        + __construct() : void
        + translation_init() : void
    }
    class Allergens_Dietary_Startup{
        +{static} on_activation : void
        +{static} on_deactivation : void
    }
    class Allergens_Dietary_Wc_Integration_Startup{
        +init_integration() : void
        +add_integration(integrations:array) : array
    }
}


N2 -- Allergens_Dietary
Allergens_Dietary +-u- php

Allergens_Dietary_Product_Settings .l.> Allergens_Dietary_Allergy_Product_Queries : uses
Allergens_Dietary_Products ..> Allergens_Dietary_Allergy_Product_Queries


' forms relations
FormType  <.. Allergens_Dietary_Form 
Allergens_Dietary_Form o-r-> I_Allergens_Dietary_Form
Allergens_Dietary_License_Form ..|> I_Allergens_Dietary_Form
@enduml