<?php

if (! defined('ABSPATH')) {
	exit;
}

if (! enum_exists('Allergens_Dietary_Notice_Types')) {
	require_once ALLERGENS_DIETARY_DIRNAME . '/php/notice/notice_Types.php';
}

/**
 * @brief This class handles the errors. 
 * and carries out potential error logs for future development
 * @author Verdi-B
 * @since 1.0.0
 * @date 4-11-2024
 */

class Allergens_Dietary_Notices
{

	private static array $instances;
	
	/**
	 * @brief singleton method to get the instance of the class
	 * @return Allergens_Dietary_Notices
	 * @author Verdi-B
	 * @since 0.17.0.0
	 * @date 18-11-2024
	 */
	public static function getInstance()
    {
        $subclass = static::class;
        if (!isset(self::$instances[$subclass])) {
            self::$instances[$subclass] = new static();
        }
        return self::$instances[$subclass];
    }

	/**
	 * @brief a protected constructor for the class
	 * sets css amongst other things
	 * @author Verdi-B
	 * @since 0.17.0.0
	 * @date 18-11-2024
	 */
	protected function __construct() {
	}
	/**
	 * @brief method that handles error notices of this plugin. Every error notice generated by this plugin will call this function, sending both the notice type(WP css class) and the(translated) message
	 * @param Allergens_Dietary_Notice_Types $type
	 * @param string $message
	 * @return void
	 * @author Verdi-B
	 * @since 1.0.0
	 * @date 4-11-2024
	 */
	public function error_notice($type, $message)
	{
		/*
		 * translators: placeholders in the __() function are there to seen as html tags when in use with sprintf()
		 */
		$message_header = sprintf(__('%1$sAllergens and Dietary is inactive:%2$s', 'allergens-dietary'), '<p><strong>', '</strong></p>');
		$message_full   = $message_header . $message;
		add_action(
			'admin_notices',
			static function () use ($type, $message_full) {
				echo '<div class="notice ' . esc_attr($type) . '" style="padding:12px 12px"> <p>
					' . wp_kses_post($message_full) . '
				</p></div>';
			}
		);

	}

	protected static function admin_notice(Allergens_Dietary_Notice_Types $type, string $message)
	{
		$message_full   = '<strong>Allergens and Dietary: </strong> '. $message;
		?>
		<div class="notice is-dismissible <?php echo esc_attr($type->value) ?>"> <p>
			<?php echo wp_kses_post($message_full) ?>
		</p></div>
		<?php
	}

	public function display_admin_notice(Allergens_Dietary_Notice_Types $type, string $message){
		add_action('admin_notices', self::admin_notice($type, $message),5);
		// add_action('admin_notices',  static function() use ($type, $message) {
		// 	self::admin_notice($type, $message);
		// });
	}

}
